### PR TITLE
impove AS sources and builds

### PR DESCRIPTION
**Pull request by MaxGraey**

### CODE REVIEW

**Comment by MaxGraey** [comment]
Also note in WebAssembly cases you're measure not only actual processing performance but also loading, init and validation of wasm module which is not really fair comparison with JS

**Comment by pretentious7** [comment]
> Also note in WebAssembly cases you're measure not only actual processing performance but also loading, init and validation of wasm module which is not really fair comparison with JS

Heya! I really should've read this before having two hours of confusion...

**Review by pretentious7 — APPROVED** [review]

**Comment by pretentious7** [comment]
> Also note in WebAssembly cases you're measure not only actual processing performance but also loading, init and validation of wasm module which is not really fair comparison with JS

Dyknow the easiest way to cache the wasm sensibly? was just planning to use https://developer.mozilla.org/en-US/docs/WebAssembly/Caching_modules

**Comment by MaxGraey** [comment]
> Dyknow the easiest way to cache the wasm sensibly?

No, I mean better organize benchmark differently.
First of all wrap main calculations/loops to some function like:
```ts
const ITER_CONST = 1000;

// ...

export function compute(
    canvas_width: i32, 
    canvas_height: i32,
    START_X_TOTAL: f32,
    START_Y_TOTAL: f32,
    WINDOW: f32
): void {
    onst step_X:f32 = WINDOW/f32(canvas_width);
    const step_Y:f32 = WINDOW/f32(canvas_height);
    for (let y = START_Y_TOTAL, count_y = 0; count_y < canvas_height; y += step_Y, count_y++){
	for (let x = START_X_TOTAL, count_x = 0; count_x < canvas_width; x += step_X, count_x++){
             store<i16>(2*(count_y*canvas_width + count_x), mandelbrot(x,y));
	}
    }
}
```

And on the host side measure only this function:
```ts

function returnSharedBufferjs(
	START_X_TOTAL, START_Y_TOTAL, canvas_width, canvas_height, WINDOW
) {
	const importObj = {
		env: {
			abort(_msg, _file, line, column) { console.error("abort!" + line + ":" + column) },
			memory
		},
	}
	return init_wasm("benchmarks/simple-assemblyscript/out/main.wasm", importObj)
	   .then(result => {
	        let t = performance.now();
	        result.exports.compute(canvas_width, canvas_height, START_X_TOTAL, START_Y_TOTAL, WINDOW);
	        t = performance.now() - t;
	        report('compute time: ' + t + 'ms'); // print benchmarked time
		draw(0, canvas_width, canvas_height);
           }).catch(console.error);
}
```

**Comment by pretentious7** [comment]
> > Dyknow the easiest way to cache the wasm sensibly?
> 
> No, I mean better organize benchmark differently.
> First of all wrap main calculations/loops to some function like:
> 
> ```ts
> const ITER_CONST = 1000;
> 
> // ...
> 
> export function compute(
>     canvas_width: i32, 
>     canvas_height: i32,
>     START_X_TOTAL: f32,
>     START_Y_TOTAL: f32,
>     WINDOW: f32
> ): void {
>     onst step_X:f32 = WINDOW/f32(canvas_width);
>     const step_Y:f32 = WINDOW/f32(canvas_height);
>     for (let y = START_Y_TOTAL, count_y = 0; count_y < canvas_height; y += step_Y, count_y++){
> 	for (let x = START_X_TOTAL, count_x = 0; count_x < canvas_width; x += step_X, count_x++){
>              store<i16>(2*(count_y*canvas_width + count_x), mandelbrot(x,y));
> 	}
>     }
> }
> ```
> 
> And on the host side measure only this function:
> 
> ```ts
> function returnSharedBufferjs(
> 	START_X_TOTAL, START_Y_TOTAL, canvas_width, canvas_height, WINDOW
> ) {
> 	const importObj = {
> 		env: {
> 			abort(_msg, _file, line, column) { console.error("abort!" + line + ":" + column) },
> 			memory
> 		},
> 	}
> 	return init_wasm("benchmarks/simple-assemblyscript/out/main.wasm", importObj)
> 	   .then(result => {
> 	        let t = performance.now();
> 	        result.exports.compute(canvas_width, canvas_height, START_X_TOTAL, START_Y_TOTAL, WINDOW);
> 	        t = performance.now() - t;
> 	        report('compute time: ' + t + 'ms'); // print benchmarked time
> 		draw(0, canvas_width, canvas_height);
>            }).catch(console.error);
> }
> ```

yep done thanks!

**Pull request merged**
